In [2]:
!pip install ultralytics
from ultralytics import YOLO
import cv2
import numpy as np
import torch

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

Setup complete. Using torch 2.4.0.dev20240326+cu121 (NVIDIA GeForce RTX 4060 Laptop GPU)


In [3]:
import torch

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

Setup complete. Using torch 2.4.0.dev20240326+cu121 (NVIDIA GeForce RTX 4060 Laptop GPU)


In [3]:
model_p = YOLO("models/Yolo5B/weights/best.pt")

In [4]:
player_result = model_p.predict('image.png')


image 1/1 c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\image.png: 640x640 (no detections), 26.4ms
Speed: 2.4ms preprocess, 26.4ms inference, 523.7ms postprocess per image at shape (1, 3, 640, 640)


In [8]:
player_result[0].boxes.shape[0] == 0

True

In [23]:
for r in player_result:
    print(r.boxes.xyxy)
    print(r.boxes.cls)
    print(r.boxes.id)

tensor([[ 488.0400,  881.0936,  535.2454, 1039.0935],
        [1821.3289,  432.3618, 1889.3145,  525.9909],
        [1369.3762,  299.8470, 1407.7039,  382.9544],
        [1724.7578,  457.2629, 1775.9778,  556.2878],
        [ 453.7208,  353.5248,  515.4503,  430.2573],
        [1467.1257,  387.8286, 1510.4506,  481.8756],
        [1034.2825,  455.0038, 1090.7876,  559.2401],
        [ 757.0642,  307.4173,  789.9924,  397.1479],
        [ 119.6113,  210.1059,  149.8779,  293.4858],
        [ 881.0756,  265.0345,  911.1882,  337.3988],
        [1098.0337,  365.8982, 1141.8589,  431.4150],
        [1833.1066,  202.2501, 1872.8141,  275.6482],
        [1111.1533,  417.2350, 1159.3800,  509.9713],
        [ 994.6929,  232.1268, 1025.5515,  312.1503],
        [ 434.6426,  462.8289,  471.4591,  559.4268],
        [ 467.5569,  475.9723,  496.1655,  582.5448],
        [ 435.9147,  462.9956,  472.5072,  564.0459],
        [1109.8151,  424.3227, 1156.4344,  511.9379],
        [1099.6854,  366.327

In [4]:
import numpy as np
player_result = model_p.track('frame_image.jpg',save = True,iou = 0.9)
player_result = player_result[0]
player_box = player_result.boxes.xyxy.cpu().numpy()
player_cls = player_result.boxes.cls.cpu().numpy() # 0 player, 1 ref, 2 ball
player_id = player_result.boxes.id.cpu().numpy()
player_xloc = np.mean(player_box[:,[0,2]],axis = 1)
player_yloc = np.min(player_box[:,[1,3]], axis = 1)
player_loc = np.hstack([np.expand_dims(player_xloc,1),np.expand_dims(player_yloc,1),np.ones_like(np.expand_dims(player_yloc,1))])


image 1/1 c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\frame_image.jpg: 384x640 16 players, 3 referees, 89.5ms
Speed: 2.0ms preprocess, 89.5ms inference, 754.9ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs\detect\track


In [44]:
player_loc

tensor([[5.1164e+02, 8.8109e+02, 1.0000e+00],
        [1.8553e+03, 4.3236e+02, 1.0000e+00],
        [1.3885e+03, 2.9985e+02, 1.0000e+00],
        [1.7504e+03, 4.5726e+02, 1.0000e+00],
        [4.8459e+02, 3.5352e+02, 1.0000e+00],
        [1.4888e+03, 3.8783e+02, 1.0000e+00],
        [1.0625e+03, 4.5500e+02, 1.0000e+00],
        [7.7353e+02, 3.0742e+02, 1.0000e+00],
        [1.3474e+02, 2.1011e+02, 1.0000e+00],
        [8.9613e+02, 2.6503e+02, 1.0000e+00],
        [1.1199e+03, 3.6590e+02, 1.0000e+00],
        [1.8530e+03, 2.0225e+02, 1.0000e+00],
        [1.1353e+03, 4.1724e+02, 1.0000e+00],
        [1.0101e+03, 2.3213e+02, 1.0000e+00],
        [4.5305e+02, 4.6283e+02, 1.0000e+00],
        [4.8186e+02, 4.7597e+02, 1.0000e+00],
        [4.5421e+02, 4.6300e+02, 1.0000e+00],
        [1.1331e+03, 4.2432e+02, 1.0000e+00],
        [1.1198e+03, 3.6633e+02, 1.0000e+00]])

: 

In [6]:

player_result = model_p.track('dataset/test.mp4',save = True,iou = 0.9)



WARNING  inference results will accumulate in RAM unless `stream=True` is passed, causing potential out-of-memory
errors for large sources or long-running streams and videos. See https://docs.ultralytics.com/modes/predict/ for help.

Example:
    results = model(source=..., stream=True)  # generator of Results objects
    for r in results:
        boxes = r.boxes  # Boxes object for bbox outputs
        masks = r.masks  # Masks object for segment masks outputs
        probs = r.probs  # Class probabilities for classification outputs

video 1/1 (frame 1/1466) c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\dataset\test.mp4: 384x640 17 players, 2 referees, 296.5ms
video 1/1 (frame 2/1466) c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\dataset\test.mp4: 384x640 17 players, 2 referees, 17.0ms
video 1/1 (frame 3/1466) c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\dataset\test.mp4: 384x640 17 players, 2 referees, 16.0ms
video 1/1 (frame 4/1466) 

In [21]:
for r in player_result:
    print(r.boxes.xyxy)
    print(r.boxes.cls)
    print(r.boxes.id)

tensor([[ 488.0400,  881.0936,  535.2454, 1039.0935]])
tensor([0.])
tensor([1.])


In [11]:
#using model_p to extract the color of the jersreys
import pandas as pd
from PIL import Image
import skimage


frame = cv2.imread('frame_image.jpg')
results_players = model_p('frame_image.jpg', conf=0.6)
frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)                

palette_list = []                                                                
palette_interval = (0,5)                           
annotated_frame = cv2.imread('frame_image.jpg')
num_colors = 2
colors = {
    "Chelsea":[(41,71,138), (220,98,88)],
    "Man City":[(144,200,255), (188,199,3)] #(Players kit color, GK kit color)
}
colors_list = colors["Chelsea"] + colors["Man City"]
color_list_lab = [skimage.color.rgb2lab([i/255 for i in c]) for c in colors_list]                           

for player, count in enumerate(list(results_players[0].boxes.cls.cpu().numpy())):
    if int(count) == 0:
        #get the box of the player
        box = results_players[0].boxes.xyxy.cpu().numpy()[player, :]                   
        obj_img = frame_rgb[int(box[1]):int(box[3]), int(box[0]):int(box[2])] 
        width, height = obj_img.shape[1], obj_img.shape[0]
        #shrink the box to incorporate less of thd grass
        x1 = np.max([(width // 2) - (width // 6), 1])
        x2 = (width // 2) + (width // 6)
        y1 = np.max([(height // 3) - (height // 6), 1])
        y2 = (height // 3) + (height // 6)
        center_filter = obj_img[y1:y2, x1:x2]
        pil_img = Image.fromarray(np.uint8(center_filter))  
        #reduce the image size to just that of the small box
        reduced = pil_img.convert("P", palette=Image.Palette.WEB)
        #find the colors of the image
        palette = reduced.getpalette()                     
        palette = [palette[3 * n:3 * n + 3] for n in range(256)]      
        color_count = [(n, palette[m]) for n, m in reduced.getcolors()]                
        RGB_df = pd.DataFrame(color_count, columns = ['cnt', 'RGB']).sort_values(
                            by = 'cnt', ascending = False).iloc[
                            palette_interval[0]:palette_interval[1], :]
        palette = list(RGB_df.RGB) 
        #shows the small boxes on each player                                            
        annotated_frame = cv2.rectangle(annotated_frame,                
                                        (int(box[0]) + x1,
                                            int(box[1]) + y1),
                                        (int(box[0]) + x2,
                                            int(box[1]) + y2), (0,0,0), 2)
    
        cv2.imwrite('small_boxes.jpg', annotated_frame)  
        palette_list.append(palette)
        players_distance_features = []
        #iterate through each palette in the lists of palettes
        for palette in palette_list:
            palette_distance = []
            palette_lab = [skimage.color.rgb2lab([i/255 for i in color]) for color in palette]
            #iterate through each of the folors in thre paleette list
            for color in palette_lab:
                distance_list = []
                #iterate thtouhg each team color to find the color with the least distacne
                for c in color_list_lab:
                    distance = skimage.color.deltaE_cie76(color, c)                             
                    distance_list.append(distance)                                              
                palette_distance.append(distance_list)                                          
            players_distance_features.append(palette_distance)                
        players_teams_list = []

        for dist in players_distance_features:
            vote = []
            for dist_list in dist:
                team_idx = dist_list.index(min(dist_list)) // num_colors                   
                vote.append(team_idx)                                              
            players_teams_list.append(max(vote, key=vote.count))
print(players_teams_list)

annotated_frame = cv2.imread('frame_image.jpg')
for i, team_index in enumerate(players_teams_list):
    box = results_players[0].boxes.xyxy.cpu().numpy()[i,:]
    annotated_frame = cv2.rectangle(annotated_frame, (int(box[0]), int(box[1])), 
                                    (int(box[2]), int(box[3])), (0, 255, 0), 2) 
    x_center = int((box[0] + box[2]) / 2)
    y_top = int(box[1])
    position = (x_center - 50, y_top - 10)
    
    team_color = (255, 255, 255) 
    if team_index == 0:
        team_color = (0, 0, 255) 
    elif team_index == 1:
        team_color = (0, 255, 0) 
    
    annotated_frame = cv2.putText(annotated_frame, f"Team: {players_teams_list[team_index]}", position,
                                  cv2.FONT_HERSHEY_SIMPLEX, 0.5, team_color, 2, cv2.LINE_AA)
cv2.imwrite('players_with_predictions.jpg', annotated_frame)


image 1/1 c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\frame_image.jpg: 384x640 14 players, 2 referees, 99.4ms
Speed: 4.3ms preprocess, 99.4ms inference, 805.8ms postprocess per image at shape (1, 3, 384, 640)
[0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0]


True

In [1]:
model_f = YOLO("models/Yolo8MF/weights/best.pt")
# model_f.predict('dataset/test.mp4',save = True,conf = 0.2)

NameError: name 'YOLO' is not defined

In [5]:
result = model_f.predict('frame_image.jpg',save = True,conf = 0.2)


image 1/1 c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\frame_image.jpg: 384x640 1 TRC, 1 TR6MC, 1 TL6MC, 1 TR6ML, 1 TL6ML, 1 TR18MC, 1 TR18ML, 1 TRArc, 1 TLArc, 1 RMC, 1 BRArc, 92.4ms
Speed: 2.0ms preprocess, 92.4ms inference, 763.3ms postprocess per image at shape (1, 3, 384, 640)
Results saved to runs\detect\predict


In [6]:

for r in result:
    print(r.boxes.xyxy)
    print(r.boxes.cls)
    box = r.boxes.xyxy.cpu().numpy()
    cls = r.boxes.cls.cpu().numpy()
print(model_f.names)


tensor([[  42.4115,   73.6438,   72.8913,  104.8323],
        [  30.9616,   98.6347,   60.1895,  128.7405],
        [1035.0713,   82.4019, 1065.2412,  112.1971],
        [ 843.8967,  431.2320,  874.1234,  461.2748],
        [  83.1459,  155.1336,  111.9179,  185.4937],
        [1113.4604,  155.9391, 1143.8699,  187.1442],
        [1487.4834,   75.8499, 1517.5239,  106.3433],
        [ 648.0400,  159.6784,  677.6522,  190.0375],
        [ 687.8273,  105.7599,  718.3786,  135.6172],
        [ 992.0807, 1043.7299, 1022.0110, 1073.2054],
        [ 675.6902,   82.1380,  706.1970,  111.9479]], device='cuda:0')
tensor([ 5.,  3.,  8., 13., 11.,  6.,  1., 10.,  2., 26.,  4.], device='cuda:0')
{0: 'TLC', 1: 'TRC', 2: 'TR6MC', 3: 'TL6MC', 4: 'TR6ML', 5: 'TL6ML', 6: 'TR18MC', 7: 'TL18MC', 8: 'TR18ML', 9: 'TL18ML', 10: 'TRArc', 11: 'TLArc', 12: 'RML', 13: 'RMC', 14: 'LMC', 15: 'LML', 16: 'BLC', 17: 'BRC', 18: 'BR6MC', 19: 'BL6MC', 20: 'BR6ML', 21: 'BL6ML', 22: 'BR18MC', 23: 'BL18MC', 24: 'BR18ML', 

TLC: top left
TRC: top right,

tr6mc: Top right 6 corner
tl6mc: top left 6 corner
tr6ml: top right 6 base
tl6ml: top left 6 base

tr18mc: Top right 18 corner
tl18mc: top left 18 corner
tr18ml: top right 18 base
tl18ml: top left 18 base

TRarc: top right arc 
TLarc: top left arc

RML: midfield right corner
RMC: midfield right circl corner

LMC: midfiled left circle corner
LML: midfield left corner

BLC: bottom left
BRC: bottom right

br6mc: bottom right 6 corner
bl6mc: bottom left 6 corner
br6ml: bottom right 6 base
bl6ml: bottom left 6 base

br18mc: bottom right 18 corner
bl18mc: bottom left 18 corner
br18ml: bottom right 18 base
bl18ml: bottom left 18 base

BRarc: bottom right arc 
BLarc: bottom left arc

In [13]:
import cv2

# Variable to store the coordinates
point = None
points = []
# Mouse callback function
def get_coordinates(event, x, y, flags, param):
    global point
    if event == cv2.EVENT_LBUTTONDOWN:
        point = (x, y)

# Load the image
image = cv2.imread('field_graph.jpg')

# Create a window and bind the mouse callback function
cv2.namedWindow('image')
cv2.setMouseCallback('image', get_coordinates)

# Main loop
while True:
    # Display the image
    cv2.imshow('image', image)

    # Wait for a key press
    key = cv2.waitKey(1) & 0xFF

    # If the 'q' key is pressed, break from the loop
    if key == ord('q'):
        break

    # If a point is selected, print its coordinates
    if point is not None:
        points.append(point)
        point = None

# Clean up
cv2.destroyAllWindows()

In [15]:
def draw_dot_with_number(image, coordinate, index):
    # Draw a dot
    cv2.circle(image, coordinate, 5, (0, 255, 0), -1)  # Green dot

    # Draw the index number
    cv2.putText(image, str(index), (coordinate[0] - 10, coordinate[1] - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)  # Red number

# Load the image
image = cv2.imread('field_graph.jpg')

# List of coordinates
  # Example coordinates

# Plot dots with numbers for each coordinate
for i, coord in enumerate(points):
    draw_dot_with_number(image, coord, i)

# Display the image
cv2.imshow('Dots with Numbers', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import numpy as np
# np.save("field_coord.npy", np.array(points))

In [9]:
transform_coord = np.load('field_coord.npy')

In [6]:
transform_coord

array([[ 28, 485],
       [ 28,  25],
       [ 76, 198],
       [ 75, 320],
       [ 27, 197],
       [ 28, 320],
       [148, 138],
       [147, 382],
       [ 27, 138],
       [ 28, 382],
       [149, 202],
       [148, 316],
       [352,  25],
       [351, 193],
       [351, 323],
       [351, 484],
       [676, 486],
       [674,  25],
       [628, 198],
       [627, 320],
       [675, 199],
       [675, 320],
       [555, 138],
       [556, 382],
       [675, 138],
       [676, 381],
       [553, 205],
       [554, 315]])

In [10]:
def draw_dot_with_number(image, coordinate, index):
    # Draw a dot
    cv2.circle(image, coordinate, 5, (0, 255, 0), -1)  # Green dot

    # Draw the index number
    cv2.putText(image, str(index), (coordinate[0] - 10, coordinate[1] - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)  # Red number

# Load the image
image = cv2.imread('field_graph.jpg')

# List of coordinates
  # Example coordinates

# Plot dots with numbers for each coordinate
for i, coord in enumerate(transform_coord):
    draw_dot_with_number(image, coord, i)

# Display the image
cv2.imshow('Dots with Numbers', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
cls = cls.astype(np.int32)
transform_coord = transform_coord[cls]


In [19]:
box
pts = np.mean(box.reshape(-1, 2, 2), axis=1)

In [20]:
pts

array([[     57.651,      89.238],
       [     45.576,      113.69],
       [     1050.2,      97.299],
       [     859.01,      446.25],
       [     97.532,      170.31],
       [     1128.7,      171.54],
       [     1502.5,      91.097],
       [     662.85,      174.86],
       [      703.1,      120.69],
       [       1007,      1058.5],
       [     690.94,      97.043]], dtype=float32)

In [21]:
pts = pts.astype(np.int16)

In [22]:
homography, _ = cv2.findHomography(pts, transform_coord)

In [29]:
image = cv2.imread('field_graph.jpg')
height, width = image.shape[:2]
image = cv2.imread('frame_image.jpg')

warped_image = cv2.warpPerspective(image, homography, (width, height))


In [30]:
cv2.imwrite('processed_image.jpg', warped_image)

True

In [10]:
model_f = YOLO("models/Yolo8MF/weights/best.pt")
cap = cv2.VideoCapture('dataset/test2.mp4')
def draw_dot_with_number(image, coordinate, index):
    # Draw a dot
    cv2.circle(image, coordinate, 5, (0, 255, 0), -1)  # Green dot

    # Draw the index number
    cv2.putText(image, str(index), (coordinate[0] - 10, coordinate[1] - 10),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 2)  # Red number
while cap.isOpened():
    success, frame = cap.read()
    if success:
        field_result = model_f.predict(frame,show = True)
        
        # for coord, i  in zip(image_kp, image_kp_cls):
        #     draw_dot_with_number(frame, coord, i)
        # cv2.imshow("YOLOv8 Tracking", frame)
        key = cv2.waitKey(0) & 0xFF
        if key == ord('c'):
            continue
        elif key == ord('q'):
            break
    else:
        break


0: 384x640 2 TRCs, 1 TR6MC, 1 TR6ML, 1 TR18MC, 2 TR18MLs, 2 TRArcs, 1 RML, 2 RMCs, 1 BR6MC, 1 BL6MC, 1 BR18MC, 1 BL18MC, 1 BRArc, 1 BLArc, 88.8ms
Speed: 2.2ms preprocess, 88.8ms inference, 210.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 TRCs, 1 TR6MC, 1 TR6ML, 1 TR18MC, 2 TR18MLs, 2 TRArcs, 1 RML, 2 RMCs, 1 BR6MC, 1 BL6MC, 1 BR18MC, 1 BL18MC, 1 BRArc, 1 BLArc, 138.6ms
Speed: 2.6ms preprocess, 138.6ms inference, 9.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 TRCs, 2 TR6MCs, 2 TR6MLs, 2 TR18MCs, 2 TR18MLs, 1 TRArc, 2 RMLs, 2 RMCs, 1 BR6MC, 1 BL6MC, 1 BR18MC, 1 BL18MC, 1 BRArc, 1 BLArc, 83.5ms
Speed: 2.4ms preprocess, 83.5ms inference, 6.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 TRCs, 1 TR6MC, 1 TR6ML, 1 TL6ML, 1 TR18MC, 2 TR18MLs, 2 TRArcs, 1 RML, 2 RMCs, 1 BR6MC, 1 BL6MC, 1 BR18MC, 1 BL18MC, 1 BRArc, 1 BLArc, 47.4ms
Speed: 2.9ms preprocess, 47.4ms inference, 7.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x

: 

In [3]:
model_f = YOLO("models/Yolo8MF/weights/best.pt")
field_result = model_f.predict('frame_image.jpg')


image 1/1 c:\Users\zhout\My Drive (walcezu@umich.edu)\EECS442\442_final\frame_image.jpg: 384x640 1 TRC, 1 TR6MC, 1 TL6MC, 1 TR6ML, 1 TL6ML, 1 TR18MC, 1 TR18ML, 1 TRArc, 1 TLArc, 1 RMC, 1 BRArc, 106.1ms
Speed: 2.0ms preprocess, 106.1ms inference, 786.5ms postprocess per image at shape (1, 3, 384, 640)


In [9]:
field_result[0].boxes[:4]

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([ 5.,  3.,  8., 13.], device='cuda:0')
conf: tensor([0.9207, 0.9173, 0.8606, 0.8603], device='cuda:0')
data: tensor([[4.2411e+01, 7.3644e+01, 7.2891e+01, 1.0483e+02, 9.2070e-01, 5.0000e+00],
        [3.0962e+01, 9.8635e+01, 6.0190e+01, 1.2874e+02, 9.1731e-01, 3.0000e+00],
        [1.0351e+03, 8.2402e+01, 1.0652e+03, 1.1220e+02, 8.6061e-01, 8.0000e+00],
        [8.4390e+02, 4.3123e+02, 8.7412e+02, 4.6127e+02, 8.6033e-01, 1.3000e+01]], device='cuda:0')
id: None
is_track: False
orig_shape: (1080, 1920)
shape: torch.Size([4, 6])
xywh: tensor([[  57.6514,   89.2380,   30.4799,   31.1884],
        [  45.5756,  113.6876,   29.2279,   30.1058],
        [1050.1562,   97.2995,   30.1699,   29.7952],
        [ 859.0100,  446.2534,   30.2267,   30.0428]], device='cuda:0')
xywhn: tensor([[0.0300, 0.0826, 0.0159, 0.0289],
        [0.0237, 0.1053, 0.0152, 0.0279],
        [0.5470, 0.0901, 0.0157, 0.0276],
        [0.4474, 0.4132, 0

In [9]:
frame = cv2.imread('image.png')
frame_width = frame.shape[1]
frame_height = frame.shape[0]


# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'H264')  # You can also use 'MP4V' for .mp4
out = cv2.VideoWriter('output_video.mp4', fourcc, 25.0, (frame_width, frame_height))
out.write(frame)
out.release()